
import { test, expect } from '@playwright/test';

// this script 100 % generated by "codegen" recording machanism for playwright
//  "npx playwright codegen" -- terminal command
// -- this will open 2 window, 1 for playwright inspector, another for navigating website 

test('test', async ({ page }) => {
  await page.goto('https://www.saucedemo.com/');
  await page.locator('[data-test="username"]').click();
  await page.locator('[data-test="username"]').fill('muhammad islam');
  await page.locator('[data-test="username"]').press('Enter');
  await page.locator('[data-test="password"]').click();
  await page.locator('[data-test="password"]').fill('ewcewhibcbehwcwc');
  await page.locator('[data-test="login-button"]').click();
});